# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c6714daa86f61fbbdb5a95edcfbcb36a0a763f60f75b332e132a590b3abf70c2d76e172f6826d4b2f5e65ac40d6cf760063830916f511c66807da0946791544

test:
  secret_key_base: 1f9faaf91f68689757c0d2e5827b9912ae037bc24b402da22658bffd2783d20003f6c622036cf851f7dfe97aa02abde49c762b584d9e8189a6f5fc628ed0cde4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
